name: workflowHML

on:
  push:
    branches:
      - release

jobs:
  job-CI-HML:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Uso do SonarCloud
        env:
            GITHUB_TOKEN: ${{ secrets.TOKENGIT }}
            SONAR_TOKEN: ${{ secrets.SONARTOKEN }}
        run: |
          mvn -B verify sonar:sonar \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.organization=jcarlospontes \
          -Dsonar.projectKey=jcarlospontes_java-api \
          -Dsonar.language=java \
          -Dsonar.java.coveragePlugin=jacoco \
          -Dsonar.test.skip=true \

  job-CD-HML:
    needs: job-CI-HML
    runs-on: ubuntu-latest
    steps:
      - name: Setando conexao SSH do AZURE Cloud
        run: |
          mkdir -p ~/.ssh/	
          echo "$SSH_KEY" > ~/.ssh/azure-cloud.key
          chmod 600 ~/.ssh/azure-cloud.key
          cat >>~/.ssh/config <<END
          Host google-cloud
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/azure-cloud.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.AZURE_HML_USER }}
          SSH_KEY: ${{ secrets.AZURE_HML_SSH }}
          SSH_HOST: ${{ secrets.AZURE_HML_HOST }}
    
      - name: Checkout repo
        uses: actions/checkout@v3
          
      - name: Obtendo java 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
      
      - name: Fazendo Deploy no ambiente de HML
        run: |
          mvn -B -f pom.xml clean install -Dmaven.test.skip=true
          scp -r target/java-api.jar azure-cloud:/home/azureuser/projeto/
          ssh azure-cloud 'sudo systemctl start java'
